### ISSUE TITLE
Error while deploying with Portainer

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [hayabhay/frogbase#47]
Hi,

I'm trying to deploy the docker image using the compose file available with a few changes - 
```
version: "3.9"

services:
  whisper-ui:
    image: hayabhay/whisper-ui
    build: .
    container_name: whisper-ui
    networks:
      - ai
    volumes:
      - /srv/dev-disk-by-uuid-6bcdc785-ff84-4338-824f-ac76e5d9695c/docker/whisper/data:/data
    restart: unless-stopped
    ports:
      - 1010:8501

networks:
  ai:
    external: true
```

But I keep getting this error from Portainer - 
failed to deploy a stack: whisper-ui Pulling whisper-ui Warning failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3601388643/Dockerfile: no such file or directory 

What am I doing wrong?
